### ISSUE TITLE
The current resource limit setting method is not reasonable.

### ISSUE THREAD

**Issue by StevenYGui** [sudo-project/sudo#120]
Hi,
I use the strace to trace the sudo process and find that sudo attempts to set the system resource limit. The log is as follows:
prlimit64(0, RLIMIT_NOFILE, NULL, 0xaaaae30f0150) = 0
prlimit64(0, RLIMIT_NOFILE, 0xaaaae30f0140, NULL) = -1 EPERM (Operation not permitted)
prlimit64(0, RLIMIT_NOFILE, 0xaaaae30f0038, NULL) = -1 EPERM (Operation not permitted)
prlimit64(0, RLIMIT_NOFILE, 0xaaaae30f0140, NULL) = 0

However, the entire process does not directly set the maximum value. Instead, the setting is indirectly completed by setting -1. Is there a way to directly set the maximum value to avoid performance waste?

The code at:
src\limits.c   void unlimit_sudo(void)

**Comment by millert** [comment]
The reason for doing this is to prevent a user from running sudo with insufficient resources for it to function.  However, there really isn't a system-independent value for some of these, which is why sudo tries to use RLIM_INFINITY.  Depending on the system, using RLIM_INFINITY may not succeed for some limits so sudo has a fallback.
