### ISSUE TITLE
please reconsider https://github.com/sudo-project/sudo/commit/78709eaeec73c88cb24e5b7ebafb14ace63ece48

### ISSUE THREAD

**Issue by doverride** [sudo-project/sudo#125]
I suspect changes related to the entry mentioned in topic were prompted by:

https://bugzilla.redhat.com/show_bug.cgi?id=1943572

However I believe this was a miss-configuration by the reporter. SELinux blocked this access for a reason (the reason being miss-configuration).

I noticed this when i stumbled upon:

https://github.com/fedora-selinux/selinux-policy/pull/976

Initially I was under the assumption that changes attempting to "support" this miss-configuration were rejected by Sudo.

Curiosity led me to the change mentioned in the topic.

**Comment by millert** [comment]
It was related to https://bugzilla.redhat.com/show_bug.cgi?id=1910077, though I guess there are multiple bugs filed that are similar.  I didn't really like hard-coding unconfined_t like this (which is why I rejected the idea initially) so I'm going to back out the changes until such time as there is a better way to determine whether or not a user is an SELinux user.

**Comment by doverride** [comment]
That is also a miss-configuration. It is unfortunate because someone actually wrote a book (SElinux administration) on SELinux where this (bad) advice was given.

If this was an issue then it would have surfaced a long time ago. Its not like this feature was implemented yesterday. The current sudo SELinux awareness is pretty mature.

**Comment by millert** [comment]
Reverted by e22cc7253002b778a72685510ec1adee05bfb9a4
