### ISSUE TITLE
how do i set the prefix to /usr without messing up builds with a cross compiler

### ISSUE THREAD

**Issue by OldWorldOrdr** [sudo-project/sudo#180]
I'm trying to build sudo for iOS 5.1 using [this](https://github.com/tpoechtrager/cctools-port/) toolchain and i get that error

**Comment by millert** [comment]
There is a configure test for this but it seems that is not working for your toolchain.  Normally, on macOS you would see the following from configure:

checking whether C compiler accepts -static-libgcc... no

You can work around this by setting ax_cv_check_cflags___static_libgcc=no in the environment when running configure.  Since this works as expected on macOS it seems likely that the problem has to do with either the toolchain or how you are trying to use it with sudo.

**Comment by OldWorldOrdr** [comment]
```
/usr/sbin/ld: .libs/term.o: warning: relocation against `sudo_term_erase' in read-only section `.text'
/usr/sbin/ld: .libs/fatal.o: relocation R_X86_64_PC32 against symbol `stderr@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
/usr/sbin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
```
getting this now.  I'm determined to get this to build.

**Comment by millert** [comment]
You are not using the cross-compiler correctly if you are getting X86_64 relocations and references to glibc symbols.  You should be targeting arm or arm64, not x86_64.  Please provide the following details:

1) how you ran configure, e.g. which flags and what target
2) how you ran make, including any overrides of CC, etc

**Comment by OldWorldOrdr** [comment]
the exact issue i was hoping to avoid by using --prefix=/usr happened.  sudo is trying to load libraries from /usr/local instead of /usr.

**Comment by OldWorldOrdr** [comment]
`--exec-prefix=/usr`
