### ISSUE TITLE
A few questions about tls_init()

### ISSUE THREAD

**Issue by BornThisWay** [sudo-project/sudo#206]
https://github.com/sudo-project/sudo/blob/9c694e9a658787f58fdbe1c81e6ed6387a6ce9b4/plugins/sudoers/log_client.c#L184
```
    const char *errstr;
    debug_decl(tls_init, SUDOERS_DEBUG_PLUGIN);

    /* Only attempt to initialize TLS once, the parameters don't change. */
    if (closure->ssl_initialized) {
        if (closure->ssl == NULL)
            debug_return_bool(false);
        SSL_clear(closure->ssl);
        debug_return_bool(true);
    }

    closure->ssl_initialized = true;
    SSL_library_init();
    OpenSSL_add_all_algorithms();
    SSL_load_error_strings();
```

1. Is it more appropriate to put `closure->ssl_initialized = true` at the end of the function? After all, the intermediate processing may fail.
2. Why do you call `SSL_clear()` on repeated initializations, I see `closure->ssl` is part of the successful initialization(`closure->ssl = SSL_new(closure->ssl_ctx))`.
3. Based on 2, maybe we should set `closure->ssl` to NULL after calling SSL_clear().

Look forward to your reply. Thank you.

**Comment by millert** [comment]
1. The reason for setting it early is that if we get a failure, subsequent attempts are likely to fail too since nothing has really changed.  The check for `closure->ssl == NULL` means we return early if `tls_init()` failed the last time it was used. 
2. The purpose of `SSL_clear()` is to be able to reuse the existing `closure->ssl` pointer.
3. No, that would defeat the purpose.  `SSL_clear()` doesn't free the ssl pointer, it resets the `SSL` data structure so it can be used again.

**Comment by BornThisWay** [comment]
Ok, thank you for your answer.
