### ISSUE TITLE
Are CVE-2019-19232 and CVE-2019-19234 considered vulnerabilities?

### ISSUE THREAD

**Issue by nh2** [sudo-project/sudo#21]
As packagers ([see here](https://github.com/NixOS/nixpkgs/issues/77272)) we were wondering about these two CVEs reported about sudo:

* [CVE-2019-19232](https://nvd.nist.gov/vuln/detail/CVE-2019-19232) CVSSv3=7.5
* [CVE-2019-19234](https://nvd.nist.gov/vuln/detail/CVE-2019-19234) CVSSv3=7.5

The debian post on https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=947225#5 claims that `sudo-1.8.30` fixes the issues.

However, I cannot find the fix in the linked changelog, nor on https://github.com/sudo-project/sudo/compare/SUDO_1_8_29...SUDO_1_8_30

Do you consider them vulnerabilities/issues and were they already, or will they be, fixed?

Thanks!

**Comment by millert** [comment]
I don't consider those to bevulnerabilities; sudo is doing exactly what the sudoers file is configured to permit.  There are, however, some relevant changes in sudo 1.8.30.  Specifically the following listed in the NEWS file:

* The new allow_unknown_runas_id sudoers setting can be used to
   enable or disable the use of unknown user or group IDs.  Previously,
   sudo would always allow unknown user or group IDs if the sudoers
   entry permitted it, including via the "ALL" alias.  As of sudo
   1.8.30, the admin must explicitly enable support for unknown IDs.

 * The new runas_check_shell sudoers setting can be used to require
   that the runas user have a shell listed in the /etc/shells file.
   On many systems, users such as "bin", do not have a valid shell
   and this flag can be used to prevent commands from being run as
   those users.

**Comment by nh2** [comment]
Thank you, all clear!

**Comment by sopos** [comment]
I'm having internal discussion regarding CVE-2019-19234. If it is a real CVE and we would like to really fix it we would need to involve another pam account calls for the target user to actually check its account state.
Now, there's my question @millert. Would it make sense to you to add more pam calls to address this? To be on the safe side it should be optional via some variable, like pam_target_acct_mgmt.

**Comment by t8m** [comment]
I agree that this is not a real CVE.

On the other hand there is IMHO a design flaw in the way sudo currently calls PAM.  It should basically have two separate PAM handles opened. First should be for the authentication of the requesting user and probably only pam_authenticate should be called for that. Yes, that would skip /etc/shadow expiration checks for the requesting user however it should be noted that the user is already present on the system and being able to run processes there so the expiration checks for the user aren't that much relevant. But it could be also done so the pam_acct_mgmt is called for this PAM handle and the password expiration checks are not ignored.

This PAM handle would not be opened at all for the nopasswd sudo calls.

Then, if this first step succeeds or is skipped by nopasswd, this PAM handle would be closed and another PAM handle would be opened with the PAM_USER being set to the target user. With this PAM handle all the other PAM calls would be done with the pam_acct_mgmt call as the first one. However! In contrary to what this CVE suggests the expiration or locking of password would be ignored for the target user - the PAM_NEW_AUTHTOK_REQD return value would be treated as PAM_SUCCESS. (Or alternatively this could be a new option whether to ignore this value or not.)

There is however one thing to consider - due to pam_setcred() calls being called as target user it would make sudo even closer to su in the sense of what the credentials present in the session would be.

**Comment by millert** [comment]
Note that pam_setcred() is already called with PAM_USER set to the target user (immediately before calling pam_open_session()).  While I could add a call to pam_acct_mgmt() before that it would not really be effective for the reasons you state unless PAM_NEW_AUTHTOK_REQD is treated as an error which doesn't seem like good default behavior.  It's worth noting that "su expireduser" as root also succeeds.

**Comment by t8m** [comment]
It would be effective if chage -E 0 was used to block the target user. For that setting the return value is PAM_ACCT_EXPIRED which should be honored.
