### ISSUE TITLE
sudo rpm file for aarch64 platform 

### ISSUE THREAD

**Issue by Nixia408** [sudo-project/sudo#222]
my  system is Centos7.6, I can find  sudo-1.9.5-3.el7.x86_64.rpm on official websites. but I cannot find the same version rpm file for aarch64?

**Comment by millert** [comment]
I don't have the hardware to build aarch64 packages but you can easily do it yourself.  See https://www.sudo.ws/docs/packaging/ for instructions.

**Comment by millert** [comment]
Do you have the audit-libs-devel package installed?

**Comment by Nixia408** [comment]
> Do you have the audit-libs-devel package installed?
there is no package named audit-libs-devel in centos 7 aarch64 system<img width="891" alt="image" src="https://user-images.githubusercontent.com/33612455/208796566-903d1df8-72c4-47cc-a028-e9a227054530.png">

**Comment by millert** [comment]
Centos 7 does have a audit-libs-devel package, for example http://mirror.centos.org/altarch/7/os/aarch64/Packages/audit-libs-devel-2.8.5-4.el7.aarch64.rpm.

**Comment by Nixia408** [comment]
> Centos 7 does have a audit-libs-devel package, for example http://mirror.centos.org/altarch/7/os/aarch64/Packages/audit-libs-devel-2.8.5-4.el7.aarch64.rpm.

Finally, I successfully generated the rpm file.However, during the build it prompts an error like this, does this affect the final rpm file<img width="834" alt="image" src="https://user-images.githubusercontent.com/33612455/209641091-af9a98d7-6cc1-4b8d-b60c-f9dc0cc74304.png">

**Comment by millert** [comment]
That error comes from not having the `which` utility installed and can be ignored.  The pp script was trying to locate `rpmbuild` using `which` but this failed since `which` is not installed.  It will try to run `rpmbuild` anyway so the resulting packages should be fine.  There is a minor problem due to `/bin/ed` not being present but that will only affect a few lines in the sample sudoers file which you are probably not using.

**Comment by millert** [comment]
I now have an arm64 build box and will be producing packages for RHEL, Debian, Ubuntu and SLES.
