### ISSUE TITLE
Compile fail on AIX 7.2 (conflicting types for 'ASN1_STRING_data')

### ISSUE THREAD

**Issue by Kristijan** [sudo-project/sudo#224]
Hi All,

I have an issue compiling sudo-1.9.12p1 on AIX 7200-05-05 with OpenSSL 1.1.1l 24 Aug 2021 (packaged version of OpenSSL provided by IBM).

```
$ oslevel -s
7200-05-05-2246
$ openssl version
OpenSSL 1.1.1l  24 Aug 2021
```

Error output from the `make` command

```
libtool: compile:  gcc -c -I../../include -I../.. -I. -I../../lib/zlib -I../../lib/zlib -DZLIB_CONST -D_FORTIFY_SOURCE=2 -g -O2 -fvisibility=hidden -fstack-clash-protection ./hostcheck.c  -fPIC -DPIC -o .libs/hostcheck.o
In file included from ./hostcheck.c:38:
../../include/sudo_compat.h:342:41: error: conflicting types for 'ASN1_STRING_data'
 #  define ASN1_STRING_get0_data(x)      ASN1_STRING_data(x)
                                         ^~~~~~~~~~~~~~~~
In file included from /usr/include/openssl/e_os2.h:29,
                 from /usr/include/openssl/bio.h:29,
                 from /usr/include/openssl/x509v3.h:29,
                 from ../../include/hostcheck.h:22,
                 from ./hostcheck.c:41:
/usr/include/openssl/asn1.h:570:1: note: previous declaration of 'ASN1_STRING_data' was here
 DEPRECATEDIN_1_1_0(unsigned char *ASN1_STRING_data(ASN1_STRING *x))
 ^~~~~~~~~~~~~~~~~~
In file included from ./hostcheck.c:38:
/usr/include/openssl/x509_vfy.h:362:7: error: expected ')' before '*' token
 X509 *X509_STORE_CTX_get0_cert(X509_STORE_CTX *ctx);
       ^~~~~~~~~~~~~~~~~~~~~~~~
../../include/sudo_compat.h:339:45: error: expected ')' before '->' token
 #  define X509_STORE_CTX_get0_cert(x)   ((x)->cert)
                                             ^~
make: The error code from the last command is 1.


Stop.
make: The error code from the last command is 2.


Stop.
```

Let me know if there is any further output or logs that I can provide.

**Comment by millert** [comment]
This is caused by a mismatch between the OpenSSL header files and shared libraries.  Sudo uses the -brtl linker flag which prioritizes SVR4-style shared libraries such as libssl.so over AIX-style shared libraries like libssl.a.  See https://www.ibm.com/docs/en/xl-c-aix/13.1.2?topic=descriptions-brtl for more details.

The most likely cause of the problem is that /opt/freeware/lib/libssl.so and /opt/freeware/lib/libcrypto.so are links to an older version of OpenSSL (not 1.1.1I) that do not match the headers in /usr/include/openssl, and the linker is using those libraries instead of the newer ones.  I can reproduce this same issue on an AIX 7.2 system with the AIX freeware OpenSSL RPM installed.

If you are able to move  /opt/freeware/lib/libssl.so and /opt/freeware/lib/libcrypto.so out of the way temporarily that would probably allow sudo to build, though you would need to re-run configure so that it tests the correct libraries.

A future version of sudo will use AIX-style shared libraries by default and not use the -brtl linker flag which should avoid the issue.

**Comment by Kristijan** [comment]
Thanks @millert, while I didn't have the OpenSSL RPM's installed, I did have shared libraries in /usr/lib, which after I moved out of the way (as suggested), allowed me to compile successfully.

**Comment by millert** [comment]
Sudo 1.9.13 builds AIX-style shared libraries by default which works around this problem.
