### ISSUE TITLE
1.9.15rc3-1 sudo: unable to cache group list for root, already exists

### ISSUE THREAD

**Issue by loopway** [sudo-project/sudo#322]
Testing log_subcmds on AIX 7.3 with 1.9.15rc3-1 (to resolve #289). Getting an (unrelated?) error/warning message: 

```
# sudo -l
sudo: unable to cache group list for root, already exists
...
```

**Comment by millert** [comment]
Does this happen when you run a command via sudo as well or just when you run `sudo -l`?

**Comment by loopway** [comment]
It does also happen when I run a command via sudo.

**Comment by millert** [comment]
I'm afraid I'm unable to reproduce this on an AIX 7.1 test system, but that may be due to only having local users and none via LDAP. 
 Can you try https://www.sudo.ws/testing/sudo-1.9.15rc4-1.aix73.rpm and if it has the same problem, also add the following to /etc/sudo.conf?

```
Debug sudoers.a(sudoers.so) /var/log/sudoers_debug nss@debug
```

and run `sudo -l` again?  The debug file will help me understand where the problem lies.  You can send the debug log to sudo@sudo.ws.

**Comment by loopway** [comment]
It does not happen anymore with the provided rc4 binary. Thanks!
