### ISSUE TITLE
De facto trademark violation by Microsoft

### ISSUE THREAD

**Issue by nukeop** [sudo-project/sudo#356]
Microsoft has decided to release their own tool also named sudo: https://github.com/microsoft/sudo

Since Sudo is a well established name, immediately recognizable to developers around the world, and the risk of brand confusion is extremely high (most won't know that Microsoft's knockoff isn't the real McCoy) it seems to set a dangerous precedent. In European law, even if a trademark is unregistered, its holder may oppose the subsequent registration of an identical mark if he can demonstrate the constant and consistent use of it - which is undeniable in the case of Sudo.

Will there be legal action, or at least a strongly worded letter/Github issue?

**Comment by millert** [comment]
I'm not really in a position to take legal action against Microsoft.  When I talked to a lawyer several years ago about whether "sudo" could be trademarked, the conclusion was that, at least in the US, it is difficult to trademark something that is in common use as a verb.  It is definitely the case that sudo often gets used as a verb.  If Microsoft tried to trademark sudo, that would certainly be a problem but they are not doing that.

It's really not too different from being able to run "ls" from powershell--it's not the Unix ls but it works similarly.  I don't think people are going to be confused that "sudo" in Windows is not the same as "sudo" in Linux/Unix.

**Comment by jimscard** [comment]
The comment about trademark law and objection to registration by someone else is what is usually referred to as "prior use", in that someone who used a term in a way that could be thought of as an unregistered trademark shows that they used it that way prior to the entity that was attempting to register it.  Once that prior use is verified, the trademark becomes no longer elegible for registration by the other entity.

There's plenty of evidence of prior use, and most people don't even know that there is a separate group maintaining sudo - if anything, "sudo" is seen as part of a different branded product, e.g., Linux or MacOS for most people. So there wouldn't be any risk of brand confusion.

Plus, this isn't the first time Microsoft has implemented the same type of functionality in Windows as sudo implements. In fact, back in 2009, there was a panic when people thought Microsoft had patented sudo (they [did](https://web.archive.org/web/20140701234003/http://www.maximumpc.com/article/news/microsoft_has_patented_sudo_yes_command), but only their implementation of it in Windows, a/k/a User Account Control).

So much ado about nothing here. Microsoft is again implementing a feature with their own code, since the underlying architecture of Windows and Linux/Unix are so different, the open source version wouldn't suffice.

Additionally, things like computer language specifications and command structures have generally been considered un-patentable and un-copyrightable -- a premise which allows, for example, Linux implementations to have the same command structure as Unix.…

**Comment by millert** [comment]
Closing this issue as there is really nothing to do.

**Comment by pv2b** [comment]
> Closing this issue as there is really nothing to do.

One thing that the sudo project *could* do, if they chose to, would be to at signal their disapproval to Microsoft about using the name "sudo" in this context, in the capacity of being maintaners of sudo.

There's currently a thread over at https://github.com/microsoft/sudo/discussions/23 regarding this.

Personally, I think it would be in the best interests of the sudo project to object to this kind of a namespace collision. If not, there's a risk that bug reports for Microsoft's "Sudo for Windows" might end up in the bug tracker belonging to the Sudo project, as well as making it more difficult to find correct information about the real "sudo" with a web search.

The time to do this is now, before sudo goes out of Beta and Microsoft decides they can't do a name change because it would break scripts, just as they can't remove the "curl" Powershell alias even though they even ship a real curl in Windows these days.

**Comment by jimscard** [comment]
As I've mentioned, computer command structures aren't copyrightable, and there's a long tradition, especially in the open source community, of taking advantage of that fact.  Like, for example, all the utilities in Linux distributions that have the same names, functionality and command structure as the Unix ones they were based on. 
There is nothing to be gained by a "name change". It would only hurt users and system admins by forcing them to have to create their own alias.
