### ISSUE TITLE
sudo 1.9.16.0: unable to find terminal name device 0, 0

### ISSUE THREAD

**Issue by zuzusb** [sudo-project/sudo#408]
After upgrading sudo to 1.9.16.0 version on AIX servers and running sudo commands remotely through ssh, we receive the following message as an standard error:
```
sudo: unable to find terminal name for device 0, 0
```

Is this warning/message expected on 1.9.16.0 version? Is there a way to turn it off through /etc/sudoers file?
Sudo is working as expected, we just want to avoid receiving that warning message when running it remotely through ssh.

**Comment by millert** [comment]
That warning used to be a debug message but was promoted to a warning since it should not happen.  It turns out that on AIX, when a process has no terminal the pr_ttydev field of struct psinfo is 0, not -1 like sudo was expecting.

Unfortunately, there is no way to disable the message.  It will be fixed in the next sudo release.

**Comment by zuzusb** [comment]
Thank you @millert. I appreciate your quick response.

**Comment by millert** [comment]
Fixed in sudo 1.9.16p1, available now.

**Comment by Justinzobel** [comment]
> @Justinzobel That is a different issue, fixed by [7e8f006](https://github.com/sudo-project/sudo/commit/7e8f006888ecd95957dc80a3bda06a44265d188c) and [b7efb8a](https://github.com/sudo-project/sudo/commit/b7efb8ab5b17aaccabe864a0f5aac1c4d0afe450)

Thanks, I'll await my distro upgrading to this new release.
