### ISSUE TITLE
feature: sudo cd

### ISSUE THREAD

**Issue by poige** [sudo-project/sudo#7]
As to me this is quite natural thing to have given that some directories can't be changed to beforehand due to theirs ownership and permission mode.

**Comment by millert** [comment]
This is not possible.  From the sudo FAQ:

"cd" is a shell built-in command, you can't run it as a command since a child process (sudo) cannot affect the current working directory of the parent (your shell).  In other words, "sudo cd /foo" would start a child process, change the directory and immediately exit without doing anything useful.

**Comment by poige** [comment]
That's the trivial thing that half of UNIX noobs should know.

I was talking about `sudo --cd /some/where some.exe` that would be translated into `chdir()` before running `some.exe`

**Comment by millert** [comment]
You'd be surprised how often that question gets asked.
Adding a command line option to change the cwd before running the command seems like a reasonable feature.

**Comment by poige** [comment]
Yeah, otherwise people have to tinker with `sh -c "cd… && …"` which complicates things needlessly due to they often need to be adjusted-escaped properly.

Actually, the fact this option hadn't been added to `sudo` long time ago is somewhat strange to me.

**Comment by edneville** [comment]
Unless I'm missing something, could there be room for problems here? Consider a bad example, where a sysadmin writes a util that rewrites the contents of /etc/shadow with rot13'd names, for sake of a really really bad example, to the current working directory. If you were able to cd elsewhere first then you'd potentially get (some) control of the contents of that directory. Some script authors may not expect this.

Although the current work around does not seem pretty or intuitive (maybe this could be helped with documentation) it might be safer.

Would a workable alternative be to add something to sudoers to permit the command in a variety of directories?

**Comment by poige** [comment]
> Unless I'm missing something, could there be room for problems here?

If you missing something it's already a problem. But back to q-n: if you change uid-gid first and then try to change current directory it's not any different as if that user would try to do that. Unless I'm missing something ©

**Comment by edneville** [comment]
Some scripts may be written from the point if view that cd isn't going 
to work first. For example, sudoers.d. You probably don't want output 
going there.

Does that make sense?

**Comment by poige** [comment]
No, you're saying absolutely strange things.
Scripts, sudoers.d — O_o
if you don't want to use `--cd` (`--set-cwd` — whatever) with `sudo`, you're free to skip using it.

**Comment by millert** [comment]
I think Ed's point is that the cwd may influence the behavior of the running program.  Just because you are allowed to run a command as a certain user doesn't necessarily mean it is safe to allow the cwd to be changed to an arbitrary location as that user.  The security policy should have some control over this.

There are two things that could be useful here:

1. Allow sudoers to specify the cwd the command will run in.  E.g. CWD=/some/path before the command
2. Provide a way in sudoers to whitelist directories the user may specify with --cd (or whatever), including a wildcard or ALL entry

That way the policy is still in control.

**Comment by poige** [comment]
If you’re allowed to become that user you’re allowed to do whatever you want as that user. Rebooting server, for e. g.. Compared to that changing current working directory is pure nothing.
I don’t see reasonable conclusion why any program being run under specified uid would work incorrectly if beforehand current working directory was set to anything that it’s allowed by path’s permissions for that user. All programs that depend on cwd should start with enforcing changing current working directory they need (obviously).

**Comment by millert** [comment]
Sudo gives access to specific commands so I don't think your argument is valid.

**Comment by poige** [comment]
commands or programs?

**Comment by millert** [comment]
Executables, but now we're splitting hairs.

**Comment by poige** [comment]
not sure what you mean but the it’s not commands but executables. Thats different story. Amy point still stays valid hence. Allowing to run an executable to user you’re allowing it to change directory to anything that’s allowed by path permissions to the same very user. And if such executable needs specific directory to be set as current it's what it does when started.

**Comment by millert** [comment]
Sudo 1.9.3 includes a -D (--chdir) command line option.  It needs to be enabled in sudoers with a line like:

Defaults runcwd=*

or it can be enabled on a per-rule basis like:

someuser ALL = CWD=* ALL
