### ISSUE TITLE
Not logging out after changing an user password

### ISSUE THREAD

**Issue by AlexzPurewoko** [sudo-project/sudo#72]
Test case :

1. Open terminal. Access administrators by `sudo su`, then type a current password.
2. Success, then logout by `exit`.
3. After entering current user, then change a password by `passwd`. 
4. Then, access admin again by `sudo su`. Its success without type an user new password (not yet reaching a timeout)

This is the screenshot :
![Screenshot from 2020-11-11 05-45-49](https://user-images.githubusercontent.com/17692360/98743387-8d970d80-23e2-11eb-8bc7-b00c2b24d19f.png)

I think it can be a system vulnerabilities, and my idea is more safe to logout when password of current user has been changed.
I'm sorry if my english is bad. Thanks!

**Comment by noproto** [comment]
This could be implemented by storing a backup of the shadow database in sudo's private folders and comparing the mtime of the system shadow file (and corresponding shadow lines) vs the stored shadow, expiring all later sudo tickets. Technically possible, but copying around the shadow database may introduce more problems than it solves.

**Comment by millert** [comment]
A better option might be to use the date of last password change from /etc/shadow when deciding whether or not to require authentication.  There is still an assumption that authentication is password-based but I suppose it would be better than nothing.

**Comment by noproto** [comment]
Clever. I looked into it, the precision of the shadow database is full days since the last password change. That would unfortunately be much longer than the 15 normal minute sudo ticket period. Therefore using the shadow database date would cause some usability issues because you'd need to expire all of the tickets immediately in a rolling 48 hour window (to account for changes done near midnight), which in turn eliminates most all of the sudo ticket usage. Even a PAM hook is likely to have exceptions (like manual edits of shadow, and what @millert mentioned, alternative authentication methods). As far as I can tell, not much can be done without introducing new risks or usability issues.

**Comment by millert** [comment]
Closing this since it cannot really be solved by sudo.  One possible solution is to create and /etc/bash.bash_logout file that contains "sudo -k" to invalidate a user's time stamp on logout.  However, this is shell-specific and won't run if the shell doesn't exit cleanly.
