### ISSUE TITLE
Possible bug: Unexpected prompting on sudo --list (-l) when no NOPASSWD lines specified

### ISSUE THREAD

**Issue by hwalinga** [sudo-project/sudo#73]
Using `sudo -l` shows some information about what commands be invoked. Usually this command is purely informative and will just give you the information you want. 

However, if on your machine there are no NOPASSWD lines (e.g `%users ALL=(root) NOPASSWD: /sbin/poweroff`), then invoking `sudo -l` will prompt for a password and will not give you the information unless you provide a password. 

I am unsure if that is a bug, but it is unexpected and has proven to cause a problem in an automated script that relied on this behavior. https://github.com/Homebrew/install/pull/341

**Comment by millert** [comment]
This behavior is intentional.  Being able to see what commands a user is able to run through sudo without also knowing the user's password is an information leak.

This behavior is controlled by the "listpw" setting in the sudoers file.  The default value of the "listpw" is "any" which means no password is required as long as the user has at least one rule with the NOPASSWD tag applied.  To allow the user to list permissions without a password you'll need a line like the following in sudoers:

Defaults listpw = never

or simply:

Defaults !listpw
