### ISSUE TITLE
can be exploit with traitor

### ISSUE THREAD

**Issue by shaeinst** [sudo-project/sudo#94]
i tried [traitor](https://github.com/liamg/traitor) and i got sudo access. how to fix it? 
here is output 

> $ ./traitor --exploit docker:writable-socket
 
```
[+] Assessing machine state...
[+] Checking for opportunities...
[+][docker:writable-socket] Docker socket at /var/run/docker.sock is writable!
[+][docker:writable-socket] Opportunity found, trying to exploit it...
[+][docker:writable-socket] Building malicious docker image...
[+][docker:writable-socket] Creating evil container...
[+][docker:writable-socket] Starting evil container...
[+][docker:writable-socket] Backdooring host at /usr/bin/NBmg3g-7nxApAf- from guest...
[+][docker:writable-socket] Checking permissions...
[+][docker:writable-socket] Starting root shell...
[+][docker:writable-socket] Removing backdoor from host...
[+][docker:writable-socket] Removing container...
[+][docker:writable-socket] Cleaning up image...
[+][docker:writable-socket] Dropping you into a shell...
```

**Comment by millert** [comment]
I don't see what this has to do with sudo, it looks like traitor is exploiting the writable /var/run/docker.sock not sudo.

**Comment by shaeinst** [comment]
then how it is able start root shell?

**Comment by millert** [comment]
Docker runs as root.  Traitor is exploiting insecure file permissions on /var/run/docker.sock just as the output states.

**Comment by shaeinst** [comment]
docker runs as root then why it didn't ask for password?

if X requires sudo, and if i exploit X and can get access to sudo, is it vulnerability in sudo or X?

**Comment by millert** [comment]
dockerd is _already_ running as root--it needs root privileges to do its job (unless you are running it in a "rootless" configuration).  The fact that you can access a root shell via dockerd doesn't mean sudo is involved.  To use docker you usually either need to be in the docker group, in which you can run docker as a normal user, or it needs to be run as root via something like sudo.  The reason traitor is able to get a root shell is because your user can access /var/run/docker.sock either because you are in the docker group or because the socket is world-writable.
